### ISSUE TITLE
Unable to build with >=openssl-1.0.2

### ISSUE THREAD

**Issue by ultrabug** [mongodb/mongo-tools#11]
Using newer openssl library makes mongo-tools build fail because of bundled library **github.com/spacemonkeygo/openssl**.

```
Building bsondump...
# github.com/spacemonkeygo/openssl
vendor/src/github.com/spacemonkeygo/openssl/hostname.c:349:5: error: conflicting types for ‘X509_check_host’
 int X509_check_host(X509 *x, const unsigned char *chk, size_t chklen,
     ^
In file included from vendor/src/github.com/spacemonkeygo/openssl/hostname.c:73:0:
/usr/include/openssl/x509v3.h:741:5: note: previous declaration of ‘X509_check_host’ was here
 int X509_check_host(X509 *x, const char *chk, size_t chklen,
     ^
vendor/src/github.com/spacemonkeygo/openssl/hostname.c:355:5: error: conflicting types for ‘X509_check_email’
 int X509_check_email(X509 *x, const unsigned char *chk, size_t chklen,
     ^
In file included from vendor/src/github.com/spacemonkeygo/openssl/hostname.c:73:0:
/usr/include/openssl/x509v3.h:743:5: note: previous declaration of ‘X509_check_email’ was here
 int X509_check_email(X509 *x, const char *chk, size_t chklen,
```

There is one issue [1] open but it does not cover the problem above.

[1] https://github.com/spacemonkeygo/openssl/pull/26/files

**Comment by gabrielrussell** [comment]
I've filed a ticket in Jira to track this
    https://jira.mongodb.org/browse/TOOLS-641

**Comment by ultrabug** [comment]
Nice one, thx for the quick fix @gabrielrussell. Maybe then you'd also want to fix the other openssl pull request I mentionned above.

Can you maybe plan on tagging a -r1 or something of mongo-tools ? With the official 3.0.0, it would be good to avoid forcing users to downgrade their openssl lib because of mongodb.

**Comment by gabrielrussell** [comment]
There is now a r3.0.1 tag, https://github.com/mongodb/mongo-tools/tree/r3.0.1 , that includes both this fix as well as the other change you mentioned. Thanks for the bug report.

**Comment by ultrabug** [comment]
Thanks @gabrielrussell I'll check it out.
